In [58]:
#Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in
#sklearn.datasets.
import pandas as pd 
import numpy as np
import warnings

warnings.filterwarnings("ignore")

In [59]:
from sklearn.datasets import load_iris

In [60]:
iris = load_iris()

In [61]:
X = iris.data
y = iris.target

In [62]:
from sklearn.model_selection import train_test_split

In [65]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [66]:
from sklearn.preprocessing import StandardScaler

In [67]:
scaler = StandardScaler()

In [68]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [69]:
from sklearn.neighbors import KNeighborsClassifier

In [70]:
classifier = KNeighborsClassifier(n_neighbors=6,algorithm='auto')

In [71]:
classifier.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=6)

In [72]:
y_pred = classifier.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [73]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [33]:
#Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in
#sklearn.datasets.

from sklearn.datasets import load_boston

In [37]:
boston = load_boston()

In [38]:
X = boston.data
y = boston.target

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
scaler = StandardScaler()

In [46]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [47]:
from sklearn.neighbors import KNeighborsRegressor

In [48]:
regressor = KNeighborsRegressor(n_neighbors=8,algorithm='auto')

In [49]:
regressor.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=8)

In [50]:
y_pred = regressor.predict(X_test)

In [51]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [52]:
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(np.sqrt(mean_squared_error(y_test,y_pred)))

22.1672249251497
2.9377245508982037
4.708208249976811


In [53]:
from sklearn.metrics import r2_score

In [54]:
score = r2_score(y_test,y_pred)

In [55]:
score

0.707086920687622

In [56]:
## display adjusted r square 

1 - (1-score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

0.6821988812689233

In [76]:
#Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using
#cross-validation on load_iris dataset in sklearn.datasets.

from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
import numpy as np


iris = load_iris()
X = iris.data
y = iris.target

k_values = list(range(1, 11))
cv_scores_mean = []


for k in range(1,11):
    knn_classifier = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn_classifier, X, y, cv=5, scoring='accuracy')
    cv_scores_mean.append(scores.mean())


optimal_k = k_values[np.argmax(cv_scores_mean)]
optimal_score = max(cv_scores_mean)

print("Optimal K:", optimal_k)
print("Optimal cross-validation score:", optimal_score)


Optimal K: 6
Optimal cross-validation score: 0.9800000000000001


In [78]:
#Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in
#sklearn.datasets.

from sklearn.datasets import load_boston

boston = load_boston()

X = boston.data
y = boston.target

from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.33,random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.neighbors import KNeighborsRegressor

regressor = KNeighborsRegressor(n_neighbors=8,algorithm='auto')
regressor.fit(X_train,y_train)

y_pred = regressor.predict(X_test)

regressor.fit(X_train,y_train)

y_pred = regressor.predict(X_test)

from sklearn.metrics import mean_absolute_error,mean_squared_error


from sklearn.metrics import mean_absolute_error,mean_squared_error
print(mean_squared_error(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(np.sqrt(mean_squared_error(y_test,y_pred)))

from sklearn.metrics import r2_score

score = r2_score(y_test,y_pred)

score
## display adjusted r square 

1 - (1-score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)


22.1672249251497
2.9377245508982037
4.708208249976811


0.6821988812689233

In [79]:
#Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on
#load_iris dataset in sklearn.datasets.

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


iris = load_iris()
X = iris.data 
y = iris.target 


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


knn_classifier = KNeighborsClassifier(n_neighbors=3, weights='distance')

knn_classifier.fit(X_train_scaled, y_train)


y_pred = knn_classifier.predict(X_test_scaled)

print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [80]:
#Q6. Implement a function to standardise the features before applying KNN classifier.

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

def knn_classifier_with_standardization(X_train, X_test, y_train, y_test, n_neighbors=3):

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
  
    knn_classifier = KNeighborsClassifier(n_neighbors=n_neighbors)
  
    knn_classifier.fit(X_train_scaled, y_train)
    

    y_pred = knn_classifier.predict(X_test_scaled)
    
    return y_pred

In [82]:
#Q7. Write a Python function to calculate the euclidean distance between two points.

import numpy as np

def euclidean_distance(point1, point2):
  
  
    point1 = np.array(point1)
    point2 = np.array(point2)
    distance = np.linalg.norm(point1 - point2)
    return distance



In [83]:
#Q8. Write a Python function to calculate the manhattan distance between two points.

import numpy as np

def manhattan_distance(point1, point2):

    point1 = np.array(point1)
    point2 = np.array(point2)
    distance = np.sum(np.abs(point1 - point2))
    return distance

