<a href="https://colab.research.google.com/github/pratik9153/Data-Science-Assignments/blob/main/8_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
r = tf.constant(42)

In [ ]:
r

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [ ]:
r.numpy()

42

In [ ]:
d = tf.constant(3 , dtype = tf.int64)

In [ ]:
d

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [ ]:
r = tf.constant([[1,2,3],[4,5,6]])

In [ ]:
r

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
r.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
r.shape

TensorShape([2, 3])

In [ ]:
t = tf.ones([2,3])

In [ ]:
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
t = tf.zeros([4,5])

In [ ]:
t

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
cont1 = tf.constant([1,2,3])
cont2 = tf.constant([4,5,6])

result = tf.add(cont1 , cont2)

In [ ]:
result

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [ ]:
result.numpy()

array([5, 7, 9], dtype=int32)

In [ ]:
r = tf.random.normal(shape =(3,2), mean=0 , stddev=1)

In [ ]:
r

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.6679096 , -1.2515004 ],
       [-0.25420856, -1.9129632 ],
       [-0.83240455,  1.1865035 ]], dtype=float32)>

In [ ]:
s = tf.random.uniform(shape=(3,3),minval=0,maxval=1,dtype = tf.int64)

In [ ]:
s

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [ ]:
s.numpy()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
var0 = 24
var1 = tf.Variable(43)
var3 = tf.Variable([[[1,3,4],[4,5,6]]])
var0 , var1 , var3

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=43>,
 <tf.Variable 'Variable:0' shape=(1, 2, 3) dtype=int32, numpy=
 array([[[1, 3, 4],
         [4, 5, 6]]], dtype=int32)>)

In [ ]:
var3.numpy()

array([[[1, 3, 4],
        [4, 5, 6]]], dtype=int32)

In [ ]:
r = tf.Variable(32)

In [ ]:
r.assign(43)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=43>

In [ ]:
r.numpy()

43