In [ ]:
#Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you
#might choose one over the other.

Ordinal encoding assigns integer values to categorical variables based on their order, while label encoding assigns
unique integers to each category. Ordinal encoding is suitable when categories have a meaningful order, like low, 
medium, high. Label encoding is preferable when categories have no intrinsic order, like color (red, blue, green).

In [ ]:
#Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in
#a machine learning project.

Target Guided Ordinal Encoding involves encoding categorical variables based on their relationship with the target 
variable's mean or median. It's useful when preserving target-related information in ordinal encoding, such as in
risk assessment models.

In [ ]:
#Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

Covariance measures the degree to which two variables change together. It's crucial in statistical analysis as it 
indicates the direction of linear relationship between variables. Positive covariance suggests they increase 
together, negative implies one decreases as the other increases. Covariance is calculated by averaging the product 
of deviations from the means of two variables.

In [8]:
#Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,
#large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.
#Show your code and explain the output.

import pandas as pd 

data = pd.DataFrame({'colour':['red','green','blue'],
                     'size'  :['small','medium','large'],
                      'material':['wood','metal','plastic']
                    })
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

for column in data.columns:
    data[column] = encoder.fit_transform(data[column])

print(data)


   colour  size  material
0       2     2         2
1       1     1         0
2       0     0         1


In [10]:
#Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education
#level. Interpret the results.

import numpy as np


df = pd.DataFrame({'Age': [30, 40, 50, 60, 70],
                   'Income': [50000, 60000, 70000, 80000, 90000],
                   'Education': [12, 14, 16, 18, 20]})


cov_matrix = np.cov(df.T)

print("Covariance Matrix:")
print(cov_matrix)


Covariance Matrix:
[[2.5e+02 2.5e+05 5.0e+01]
 [2.5e+05 2.5e+08 5.0e+04]
 [5.0e+01 5.0e+04 1.0e+01]]


In [ ]:
    Interpretion :
    
    Positive covariance implies that the variables tend to increase or decrease together.
    Negative covariance implies that one variable tends to increase as the other decreases.
    A covariance of 0 indicates no linear relationship between the variables.

In [ ]:
#Q6. You are working on a machine learning project with a dataset containing several categorical
#variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD),
#and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for
#each variable, and why?

    Gender (Male/Female):
    For gender, a binary encoding method like one-hot encoding can be used. Each category (Male, Female) is 
    represented by a binary value (0 or 1). This method is suitable as gender has no ordinal relationship.

    Education Level (High School/Bachelor's/Master's/PhD):
    For education level, ordinal encoding can be used. The categories have a clear hierarchical order
    (High School < Bachelor's < Master's < PhD), making ordinal encoding appropriate to preserve this order.

    Employment Status (Unemployed/Part-Time/Full-Time):
    For employment status, one-hot encoding is suitable. Employment status categories do not have a clear
    ordinal relationship, and one-hot encoding preserves the categorical distinction without imposing any ordinality.

In [ ]:
#Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two
#categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/
#East/West). Calculate the covariance between each pair of variables and interpret the results.

