In [2]:
#Q1
import numpy as np
list_ = [ '1' ,'2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [5]:
type(list_)

list

In [6]:
type(array_list)

numpy.ndarray

yes , there is differnce between data types list_ is  a python list and array_list is numpy narray

In [9]:
#Q2
for i in list_:
  print(i,type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [10]:
for i in array_list:
  print(i,type(i))

1 <class 'numpy.str_'>
2 <class 'numpy.str_'>
3 <class 'numpy.str_'>
4 <class 'numpy.str_'>
5 <class 'numpy.str_'>


In [11]:
#Q3
list_

['1', '2', '3', '4', '5']

In [13]:
array_list = np.array(object = list_ , dtype = int)

In [14]:
array_list

array([1, 2, 3, 4, 5])

In [15]:
type(list_)

list

In [16]:
type(array_list)

numpy.ndarray

In [17]:
for i in list_:
  print(i,type(i))

1 <class 'str'>
2 <class 'str'>
3 <class 'str'>
4 <class 'str'>
5 <class 'str'>


In [18]:
for i in array_list:
  print(i,type(i))

1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


yes , there is differnece between the data types of list_ and array_list . Now , array_list is numpy array with integer data type.

In [19]:
#Q4
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [20]:
np.size(num_array)

6

In [21]:
np.shape(num_array)

(2, 3)

In [25]:
#Q5
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
#Q6
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])